[package]
name = "takeri"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2.workspace = true
md-5.workspace = true
hex.workspace = true
walkdir.workspace = true
rayon.workspace = true
indicatif.workspace = true
flate2.workspace = true
tar.workspace = true
reqwest.workspace = true
uuid.workspace = true
directories.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true