[workspace]
members = ["cli", "tools/takeri", "tools/shugo"]

resolver = "3"

[workspace.dependencies]
clap = {version = "4.5.53", features = ["derive"]}
sha2 = "0.10.9"
md-5 = "0.10.6"
hex = "0.4"
walkdir = "2.5.0"
rayon = "1.11.0"
indicatif = "0.18.3"
flate2 = "1.1.8"
tar = "0.4.44"
reqwest = {version = "0.13.1", features = ["blocking"]}
uuid = {version = "1.20.0", features = ["v4"]}
directories = "6.0.0"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"
chrono = {version = "0.4.43", features = ["serde"]}